import type { Linter } from 'eslint';
import { js as shared } from './shared.js';

export const rules: Linter.RulesRecord = {
  ...shared,
  'accessor-pairs': [ 'error', { getWithoutSet: false, setWithoutGet: true, enforceForClassMembers: true }],
  'array-callback-return': [ 'error', { allowImplicit: true }],
  'arrow-body-style': [ 'error', 'as-needed', { requireReturnForObjectLiteral: false }],
  'block-scoped-var': [ 'error' ],
  'callback-return': [ 'error', [ 'callback', 'next' ]],
  'capitalized-comments': [ 'error', 'always', {
    ignoreInlineComments: false, ignoreConsecutiveComments: true,
  }],
  'class-methods-use-this': [ 'error', { exceptMethods: []}],
  'complexity': 'off',
  'consistent-return': 'off',
  'consistent-this': [ 'error', 'that' ],
  'constructor-super': [ 'error' ],
  'curly': [ 'error', 'all' ],
  'default-case': [ 'error' ],
  'default-case-last': [ 'error' ],
  'eqeqeq': [ 'error', 'always' ],
  'for-direction': [ 'error' ],
  'func-name-matching': 'off',
  'func-names': 'off',
  'func-style': [ 'error', 'expression' ],
  'getter-return': [ 'error', { allowImplicit: true }],
  'global-require': [ 'error' ],
  'grouped-accessor-pairs': [ 'error', 'getBeforeSet' ],
  'guard-for-in': [ 'error' ],
  'handle-callback-err': [ 'error', 'err' ],
  'id-denylist': 'off',
  'id-length': [ 'error', {
    min: 2,
    max: Number.POSITIVE_INFINITY,
    properties: 'always',
    exceptions: [ '_', 'i', 'j', 't', 'x', 'y', 'z' ],
  }],
  'id-match': 'off',
  'init-declarations': 'off',
  'line-comment-position': [ 'error', { position: 'above' }],
  'no-template-curly-in-string': [ 'error' ],
  'no-ternary': 'off',
  'no-this-before-super': [ 'error' ],
  'no-throw-literal': [ 'error' ],
  'no-undef': [ 'error', { typeof: true }],
  'no-undefined': 'off',
  'no-undef-init': [ 'error' ],
  'no-underscore-dangle': [ 'error', {
    allow: [ '__html' ],
    allowAfterThis: false,
    allowAfterThisConstructor: false,
    allowAfterSuper: false,
    allowFunctionParams: false,
    enforceInMethodNames: true,
  }],
  'no-unexpected-multiline': [ 'error' ],
  'no-unmodified-loop-condition': [ 'error' ],
  'no-unneeded-ternary': [ 'error', { defaultAssignment: false }],
  'no-unreachable': [ 'error' ],
  'no-unreachable-loop': [ 'error' ],
  'no-unsafe-finally': [ 'error' ],
  'no-unsafe-negation': [ 'error' ],
  'no-unsafe-optional-chaining': [ 'error', { disallowArithmeticOperators: true }],
  'no-unused-expressions': [ 'error', {
    allowShortCircuit: false,
    allowTernary: false,
    allowTaggedTemplates: false,
  }],
  'no-unused-labels': [ 'error' ],
  'no-useless-backreference': [ 'error' ],
  'no-useless-call': [ 'error' ],
  'no-useless-catch': [ 'error' ],
  'no-useless-computed-key': [ 'error', { enforceForClassMembers: true }],
  'no-useless-concat': [ 'error' ],
  'no-useless-escape': [ 'error' ],
  'no-useless-rename': [ 'error', {
    ignoreDestructuring: false,
    ignoreImport: false,
    ignoreExport: false,
  }],
  'no-useless-return': [ 'error' ],
  'no-var': [ 'error' ],
  'no-void': [ 'error' ],
  'no-warning-comments': 'off',
  'no-with': [ 'error' ],
  'object-shorthand': [ 'error', 'always', {
    avoidQuotes: false,
    ignoreConstructors: false,
    avoidExplicitReturnArrows: true,
  }],
  'one-var': 'off',
  'operator-assignment': [ 'error', 'always' ],
  'prefer-arrow-callback': [ 'error', {
    allowNamedFunctions: false,
    allowUnboundThis: true,
  }],
  'prefer-const': [ 'error', {
    destructuring: 'any',
    ignoreReadBeforeAssign: true,
  }],

  // Arrays are disabled here because of the unicorn/noUnreadableArrayDestructuring
  // rule.
  'prefer-destructuring': [ 'error',
    { array: false, object: true },
    { enforceForRenamedProperties: false },
  ],
  'prefer-exponentiation-operator': [ 'error' ],
  'prefer-named-capture-group': [ 'error' ],
  'prefer-numeric-literals': [ 'error' ],
  'prefer-object-spread': [ 'error' ],
  'prefer-promise-reject-errors': [ 'error', { allowEmptyReject: false }],
  'prefer-regex-literals': [ 'error' ],
  'prefer-rest-params': [ 'error' ],
  'prefer-spread': [ 'error' ],
  'prefer-template': [ 'error' ],
  'radix': [ 'error', 'always' ],
  'require-atomic-updates': 'off',
  'require-unicode-regexp': [ 'error' ],
  'require-yield': [ 'error' ],
  'sort-imports': [ 'error', {
    ignoreCase: true,
    ignoreDeclarationSort: false,
    ignoreMemberSort: false,
    memberSyntaxSortOrder: [
      'single',
      'multiple',
      'all',
      'none',
    ],
  }],
  'sort-keys': 'off',
  'sort-vars': [ 'error', { ignoreCase: true }],
  'strict': [ 'error', 'global' ],
  'symbol-description': [ 'error' ],
  'unicode-bom': [ 'error', 'never' ],
  'use-isnan': [ 'error', { enforceForSwitchCase: true }],
  'valid-typeof': [ 'error', { requireStringLiterals: true }],
  'vars-on-top': [ 'error' ],
  'yoda': [ 'error', 'never', {
    exceptRange: true, onlyEquality: false,
  }],
};
